---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-app
  namespace: devops-tools
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: bonita-app
      tiers: backend
  template:
    metadata:
      labels:
        app: bonita-app
        tiers: backend
    spec:
      initContainers:
      - name: install
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo '#!/bin/bash' > /work-dir/bonita.sh
            echo 'sed -i "s/^org.bonitasoft.level = WARNING$/org.bonitasoft.level = FINEST/" /opt/bonita/BonitaCommunity-2021.1/server/conf/logging.properties' >> /work-dir/bonita.sh
            chmod +x /work-dir/bonita.sh
        volumeMounts:
        - name: custom-workdir
          mountPath: "/work-dir"
      volumes:
      - name: custom-workdir
        emptyDir: {}
      containers:
        - name:  bonita-app
          image: bonita:latest
          imagePullPolicy: Always
          env:
            - name: TENANT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: bonita-tenant-secret
                  key: username
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-tenant-secret
                  key: password
            - name: PLATFORM_LOGIN
              value: pfadmin
            - name: PLATFORM_PASSWORD
              value: pfsecret
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080
              name: bonita-app
          volumeMounts:
          - name: custom-workdir
            mountPath: /opt/custom-init.d

