---
apiVersion: v1
kind: Service
metadata:
  name: bonita-app
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: bonita-app
    tiers: backend
  ports:
    - port: 8080
      targetPort: 8080