kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bonita-pv-claim
  namespace: devops-tools
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi